# Generated by Django 5.2.8 on 2025-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_remove_orderitem_order_remove_orderitem_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='note',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
